### ISSUE TITLE
RSS Feed Broken

### ISSUE THREAD

**Issue by maxprehl** [nelsonjchen/mindflakes.com#4]
Hi Neslon,

Very impressed with the GHW-SEE project! Went to read your [blog](https://mindflakes.com/) and follow on RSS but it seems like the [RSS mechanism](https://mindflakes.com/index.xml) is a little broken.  Instead of getting the full listing of posts, it just shows links to your Projects and Posts pages.

![image](https://user-images.githubusercontent.com/39207309/155501306-da68b4bf-7d0c-47e4-917e-69f5169bea76.png)

Unfortunately, I have no experience with Hugo otherwise I'd offer to help!  Thanks again for your work with GHWSEE!

**Comment by nelsonjchen** [comment]
Hmm, it may have broken in the switch to netlify. I'll check it when time permits. Thanks!

**Comment by nelsonjchen** [comment]
I think I got it. It should be working again. Thanks for looking into this!
